services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV:-dev}
    volumes:
      - ./src:/app/src
      - ./bin:/app/bin
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock